### ISSUE TITLE
Errors running chat demo

### ISSUE THREAD

**Issue by remaininlight** [redwood/redwood#78] opened 2021-02-25 13:03 UTC
Hey, I'm excited by the potential of Redwood and Braid - would love to get involved but I'm having difficulty getting started with the chat demo. When I try on master branch, running:
$ redwood --config ./node1.redwoodrc

Gives errors like these:
```
W0225 12:48:08.640523                  host.go:0409] [host]           could not get peer at libp2p /ip4/147.75.70.221/udp/4001/quic/p2p/Qme8g49gm3q4Acp7xWBKg3nAa9fxZ1YmyDJdyGgoG6LsXh/p2p-circuit: could not parse PeerInfo from multiaddr '/ip4/147.75.70.221/udp/4001/quic/p2p/Qme8g49gm3q4Acp7xWBKg3nAa9fxZ1YmyDJdyGgoG6LsXh/p2p-circuit': invalid p2p multiaddr
W0225 12:48:08.640532                  host.go:0409] [host]           could not get peer at libp2p /ip4/147.75.70.221/tcp/4001/p2p/Qme8g49gm3q4Acp7xWBKg3nAa9fxZ1YmyDJdyGgoG6LsXh/p2p-circuit: could not parse PeerInfo from multiaddr '/ip4/147.75.70.221/tcp/4001/p2p/Qme8g49gm3q4Acp7xWBKg3nAa9fxZ1YmyDJdyGgoG6LsXh/p2p-circuit': invalid p2p multiaddr
E0225 12:48:08.640839                  host.go:0415] [host]           error verifying peer identity: (peer 12D3KooWAdbnycSEAmWsmotrbsQ5xeNBHgDhYaD7Erijw7zNjmrV): dial backoff: connection failed 
E0225 12:48:08.800731                  host.go:0415] [host]           error verifying peer identity: protocol not supported 
E0225 12:48:08.800732                  host.go:0415] [host]           error verifying peer identity: protocol not supported
```

Then running:
$ redwood --config ./node1.redwoodrc

Gives errors like these:
```
E0225 12:48:00.136619                  host.go:0415] [host]           error verifying peer identity: protocol not supported 
E0225 12:48:00.136659                  host.go:0415] [host]           error verifying peer identity: protocol not supported 
E0225 12:48:00.560400                  host.go:0415] [host]           error verifying peer identity: (peer 12D3KooWAdbnycSEAmWsmotrbsQ5xeNBHgDhYaD7Erijw7zNjmrV): failed to dial 12D3KooWAdbnycSEAmWsmotrbsQ5xeNBHgDhYaD7Erijw7zNjmrV: all dials failed
  * [/ip4/147.75.70.221/tcp/54980] dial tcp4 147.75.70.221:54980: connect: connection refused: connection failed 
E0225 12:48:09.972276                  host.go:0415] [host]           error verifying peer identity: (peer 12D3KooWAdbnycSEAmWsmotrbsQ5xeNBHgDhYaD7Erijw7zNjmrV): dial backoff: connection failed 
E0225 12:48:10.134121                  host.go:0415] [host]           error verifying peer identity: protocol not supported 
E0225 12:48:10.134147                  host.go:0415] [host]           error verifying peer identity: protocol not supported 
D0225 12:48:10.738451      transport.libp2p.go:1361] [libp2p]         libp2p disconnected: /ip4/127.0.0.1/tcp/21231/p2p/16Uiu2HAmLLpZ2tCFYPgSw1jS26HLueidnfnhfJJaRbDyavSFxnpj
```

Then running `$ node setup.js` in the chat directory gives:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../../braidjs/braid-src.js'
Require stack:
- /Users/user/Bounce/open-source/redwood/demos/chat/setup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/user/Bounce/open-source/redwood/demos/chat/setup.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/user/Bounce/open-source/redwood/demos/chat/setup.js' ]
}
```

When I switch to develop branch and run `$ go install` in repo root it wants go-structomancer, and says to run: 
$ go get github.com/brynbellomy/go-luaconv@v0.0.0-20160402002339-1f84b1d2470d

However, then when I cd into cmd and run:
$ go build --tags static -o /usr/local/bin/redwood .

It gives these errors:
```
# redwood.dev/cmd
./main.go:132:34: not enough arguments in call to redwood.NewPeerStore
        have ()
        want (*tree.DBTree)
./main.go:151:48: not enough arguments in call to redwood.NewLibp2pTransport
        have (types.Address, uint, string, *redwood.EncryptingKeypair, redwood.ControllerHub, redwood.RefStore, *redwood.peerStore)
        want (types.Address, uint, string, string, *redwood.EncryptingKeypair, redwood.ControllerHub, redwood.RefStore, redwood.PeerStore)
./main.go:173:44: not enough arguments in call to redwood.NewHTTPTransport
        have (string, string, redwood.ControllerHub, redwood.RefStore, *redwood.peerStore, *redwood.SigningKeypair, *redwood.EncryptingKeypair, [32]byte, string, string, bool)
        want (string, string, string, redwood.ControllerHub, redwood.RefStore, redwood.PeerStore, *redwood.SigningKeypair, *redwood.EncryptingKeypair, [32]byte, string, string, bool)
./main.go:203:33: too many arguments in call to redwood.NewHTTPRPCServer
        have (types.Address, string, redwood.Host)
        want (types.Address, redwood.Host)
./main.go:205:16: httpRPC.Start undefined (type *redwood.HTTPRPCServer has no field or method Start)
./main.go:231:30: not enough arguments in call to host.Subscribe
        have (context.Context, string, number, nil)
        want (context.Context, string, redwood.SubscriptionType, tree.Keypath, *redwood.FetchHistoryOpts)
```

Any advice on how to get started is gratefully received, or even if Redwood is the right place to start getting into Braid from.

**Comment by hamoser** [comment] 2021-02-26 23:32
I just ran into the same kind of issue in the text editor demo and it seems to be caused by the braidjs directory not being in the repo root.

**Comment by brynbellomy** [comment] 2021-02-27 02:58
@remaininlight @hamoser Unfortunately, the work we're doing on the latest demo has broken the other demos. I'm going to get this fixed over the next ~24 hours. Please stand by!

**Comment by remaininlight** [comment] 2021-02-27 09:48
No rush @brynbellomy! Just checking whether I was doing something wrong :)

**Comment by brynbellomy** [comment] 2021-03-02 03:01
@remaininlight @hamoser Well, 24 hours was overly optimistic. Nevertheless, good news: the `chat`, `text-editor`, and `git-integration` demos are all working again. They're up for review in this PR: #82 in case you want to check them out right away (the relevant branch is `brynbellomy/update-demos`). This PR should be merged into `develop` shortly.

**Comment by brynbellomy** [comment] 2021-03-02 05:50
Merged! https://github.com/brynbellomy/redwood/pull/82 🌲🌲🌲

**Closed as completed by brynbellomy** 2021-03-02 05:50 UTC
Labels: bug, demos
